### ISSUE TITLE
(Certain) Cryptonight algorithms broken on VAES-supporting CPUs

### ISSUE THREAD

**Issue by theAeon** [MoneroOcean/xmrig#82]
**Describe the bug**
XMRig throws "thread #x self-test failed and fails to start mining.

**To Reproduce**
Mine cn/ccx, cn-lite/1, cn, cn/r, cn/2, cn/pico or cn/gpu (possibly others) on a CPPU that supports VAES instructions. (Zen 3, Ice Lake, Tiger Lake, Alder Lake)

**Expected behavior**
It mines.

**Required data**
 - Miner log as text or screenshot - literally what i described above
 - tested with various config combinations, none worked
 - OS: tested on windows, gcc and msvc, and on wsl2.

**Additional context**
Problem is _exclusive_ to the MO fork. Vanilla xmrig works fine.

**Comment by trevor-powdrell** [comment]
Describe the bug
XMRig throws "thread #x self-test failed and fails to start mining.

To Reproduce
Start XMRIG on Zen 3 (AMD Ryzen 5 5600G)  on v6.16.1-mo2

Expected behavior
It mines

Required data
- Miner log as text or screenshot - log attached
- OS: tested on windows, gcc

[xmrig.log](https://github.com/MoneroOcean/xmrig/files/7636471/xmrig.log)

**Comment by theAeon** [comment]
Would like to note that I personally tested this on a 5600x and a 1065G7.

**Comment by ataa** [comment]
Facing the same issues on 5950X, 5900X and 5600X. Built Xmrig from source using MSYS. (3800f67, Windows 10). Cuda seems to be broken as well. reverting back to older version fixed the issue for me.

**Comment by trevor-powdrell** [comment]
Quick update.  Changing config.json in the cpu  section   "hw-aes": false lets the benchmarking complete and to start running. 
So this does seem to be related to the hw-aes code.

**Comment by theAeon** [comment]
Do you have any idea if its invoking the VAES code when AES is off? Theoretically it shouldn't depend on AES proper being enabled. If the performance didn't tank when you disabled AES, that's probably the case.

Means whatever the issue is is probably related to xmrig attempting to run both pathways.

**Comment by bkuhls** [comment]
Fixed by https://github.com/xmrig/xmrig/pull/2772 ?

**Comment by theAeon** [comment]
> Fixed by [xmrig#2772](https://github.com/xmrig/xmrig/pull/2772) ?

is that an "is this fixed" or is that a "this is fixed"

**Comment by bkuhls** [comment]
> > Fixed by [xmrig#2772](https://github.com/xmrig/xmrig/pull/2772) ?
> 
> is that an "is this fixed" or is that a "this is fixed"

It is an "is this fixed"-question. Cleanly backporting the commit is not possible due to xmrig-mo specific changes so as a user I will wait for the next rebase with https://github.com/xmrig/xmrig/releases/tag/v6.16.2

**Comment by bkuhls** [comment]
> Describe the bug XMRig throws "thread #x self-test failed and fails to start mining.

Still broken with xmrig-mo as of git rev 615715e2152db758747014abe40a5b2d4a74c13e
```
 * ABOUT        XMRig/6.16.2-mo1 gcc/10.2.1
 * LIBS         libuv/1.40.0 OpenSSL/1.1.1k hwloc/2.4.1
 * HUGE PAGES   supported
 * 1GB PAGES    supported
 * CPU          AMD Ryzen 9 5950X 16-Core Processor (1) 64-bit AES
```

**Comment by SChernykh** [comment]
It's broken on CN_GPU because of
https://github.com/MoneroOcean/xmrig/blob/master/src/crypto/cn/CryptoNight_x86.h#L412
and
https://github.com/MoneroOcean/xmrig/blob/master/src/crypto/cn/CryptoNight_x86.h#L419
and other places where `props.isHeavy()` is used without also checking for `CN_GPU`.

**Comment by bkuhls** [comment]
> It's broken on CN_GPU

Can confirm that a build with -DWITH_CN_GPU=OFF does not crash anymore.

**Comment by MoneroOcean** [comment]
@SChernykh v6.16.2-mo2 will hopefully have this fixed.

Can not test this myself, so I would appreciate if it someone will do it here :)

**Comment by bkuhls** [comment]
> @SChernykh v6.16.2-mo2 will hopefully have this fixed.
> 
> Can not test this myself, so I would appreciate if it someone will do it here :)

Yes, v6.16.2-mo2 fixes the problem, no cmake options are needed for a working build anymore, thanks!

**Comment by MoneroOcean** [comment]
Great!
